services:
  frontend:
    build: ./frontend
    depends_on:
      - ticket-service
      - support-service
      - notification-service
      - reporting-service

  ticket-service:
    build: ./ticket-service
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tickets_db
      NOTIFICATION_SERVICE_URL: http://notification-service:5002
    depends_on:
      - db
      - notification-service

  support-service:
    build: ./support-service
    environment:
      TICKET_SERVICE_URL: http://ticket-service:5000
      NOTIFICATION_SERVICE_URL: http://notification-service:5002
    depends_on:
      - ticket-service
      - notification-service

  notification-service:
    build: ./notification-service

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets_db
    volumes:
      - mysql_data:/var/lib/mysql

  reporting-service:
    build: ./reporting-service
    environment:
      TICKET_SERVICE_URL: http://ticket-service:5000
    depends_on:
      - ticket-service

volumes:
  mysql_data:
