services:
  ticket-service:
    build: ./ticket-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  support-service:
    build: ./support-service
    ports:
      - "5001:5001"
    depends_on:
      - ticket-service
      - notification-service   # 👈 important

  notification-service:
    build: ./notification-service
    ports:
      - "5002:5002"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: